apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      restartPolicy: Never
  nodeSelector:
    disktype: ssd
